### ISSUE TITLE
[Bug] Entities are invisible

### ISSUE THREAD

**Issue by reo-ar** [ZekerZhayard/OptiForge#24] opened 2020-06-18 15:34 UTC
## Description

Entities are invisible when shaders are enabled, I am not sure if Optiforge will be able to mitigate the said issue.

## How to Reproduce

Load into world and see that every entity is not rendered.

## Test Environment

**OptiFine Version**: 1.15.2_HD_U_G1_pre26
**Forge Version**: 31.2.20
**Minecraft Version**: 1.15.2
**Java Version**: AdoptOpenJDK Nightly 1.8.0_262
**Operating System**: Windows 10

Note: I will attach logs if needed.

Relevant issue: 
https://github.com/sp614x/optifine/issues/4107

**Comment by ZekerZhayard** [comment] 2020-06-18 17:04
Can you provide screenshots with shaders disabled and enabled?

**Comment by reo-ar** [comment] 2020-06-20 05:55
![Shaders Off](https://user-images.githubusercontent.com/16609399/85193705-dc030e80-b27f-11ea-9eb6-c7d258841d5d.png)
![Shaders On](https://user-images.githubusercontent.com/16609399/85193710-eb825780-b27f-11ea-9931-d08a0863a226.jpg)

These are both in third person view

**Comment by ZekerZhayard** [comment] 2020-06-20 06:12
Can't reproduced. Which shader do you use?

**Comment by reo-ar** [comment] 2020-06-20 09:24
BSL / Ymir / Kappa Shaders all produce this bug

Edit: Also tested on the All The Mods 5 pack more reliably by others

**Comment by Bopler** [comment] 2020-06-28 01:59
I have this issue with mods that render 2d entities, can reproduce with Neat & Create's Wand of Symmetry. Might help figuring out what the issue is.

**Comment by ZekerZhayard** [comment] 2020-08-17 13:51
has been fixed by optifine

**Closed as completed by ZekerZhayard** 2020-08-17 13:51 UTC
Labels: bug, wontfix
